# Generated by Django 4.2.2 on 2023-06-30 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizcategory",
            name="id",
        ),
        migrations.AlterField(
            model_name="quizcategory",
            name="title",
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="imageQuizQnA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("question", models.ImageField(upload_to="")),
                ("answer", models.TextField()),
                (
                    "quiz_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagequizqna",
                        to="quiz.quizcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
