# Generated by Django 4.2.2 on 2023-07-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_quizcategory_id_alter_quizcategory_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizcategory",
            name="title_kor",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagequizqna",
            name="question",
            field=models.ImageField(upload_to="%Y/%m/%d"),
        ),
    ]
